columnSuffix: zjbaxzci
contentColumnType: text
fieldGroup: 19fd73a5-2f81-42dd-8a69-2bcbd0c4053a # Common
handle: pageContent
instructions: ''
name: 'Page Content'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: '1'
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
