defaultPlacement: end
enableVersioning: true
handle: blogEntries
name: 'Blog Entries'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  f5fef398-ac72-479d-a160-6c3a943f3704: # CraftDev
    enabledByDefault: true
    hasUrls: true
    template: blog/_entry
    uriFormat: 'blog/{slug}'
type: channel
